import { Product } from '../../entities/models/product.interface';

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'p1',
    name: 'Modern Fabric Sofa',
    description: 'Comfortable modern sofa with a minimalist design and soft gray upholstery.',
    price: 799.99,
    imageUrl: '/photo-1505691938895-1758d7feb511?auto=format&fit=crop&w=300&q=60',
    rating: 4.6,
    reviewsCount: 124,
    inStock: true,
    category: 'home',
    reviews: [
      {
        id: 'r1',
        productid: 'p100',
        userName: 'Alice Johnson',
        userImageUrl: 'https://randomuser.me/api/portraits/women/20.jpg',
        rating: 5,
        title: 'Excellent quality!',
        comment: 'The product exceeded my expectations, highly recommend.',
        reviewDate: new Date('2024-01-15'),
      },
      {
        id: 'r15',
        productid: 'p107',
        userName: 'Olivia Garcia',
        userImageUrl: 'https://randomuser.me/api/portraits/women/55.jpg',
        rating: 2,
        title: 'Poor quality',
        comment: 'Not worth the money.',
        reviewDate: new Date('2024-09-01'),
      },
      {
        id: 'r21',
        productid: 'p107',
        userName: 'Paul Jordan',
        userImageUrl: 'https://randomuser.me/api/portraits/men/45.jpg',
        rating: 2,
        title: 'Not cosy',
        comment: 'Waist of money.',
        reviewDate: new Date('2024-07-11'),
      },
    ],
  },
  {
    id: 'p2',
    name: 'Ergonomic Office Chair',
    description: 'Chair with lumbar support and adjustable armrests.',
    price: 199.49,
    imageUrl:
      '/photo-1688578735427-994ecdea3ea4?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8RXJnb25vbWljJTIwT2ZmaWNlJTIwQ2hhaXJ8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&q=60&w=300',
    rating: 4.8,
    reviewsCount: 315,
    inStock: true,
    category: 'office',
    reviews: [
      {
        id: 'r2',
        productid: 'p100',
        userName: 'Bob Smith',
        userImageUrl: 'https://randomuser.me/api/portraits/men/45.jpg',
        rating: 4,
        title: 'Very good',
        comment: 'Solid build, works as described.',
        reviewDate: new Date('2024-02-10'),
      },
    ],
  },
  {
    id: 'p3',
    name: 'Wireless Headphones',
    description: 'Wireless headphones with noise cancellation.',
    price: 129.99,
    imageUrl:
      '/photo-1612465289702-7c84b5258fde?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OHx8V2lyZWxlc3MlMjBIZWFkcGhvbmVzfGVufDB8fDB8fHww&auto=format&fit=crop&q=60&w=300',
    rating: 4.5,
    reviewsCount: 542,
    inStock: true,
    category: 'electronics',
    reviews: [
      {
        id: 'r3',
        productid: 'p101',
        userName: 'Carla Mendes',
        userImageUrl: 'https://randomuser.me/api/portraits/women/15.jpg',
        rating: 3,
        title: 'Average',
        comment: 'It’s okay, but I expected more features.',
        reviewDate: new Date('2024-03-05'),
      },

      {
        id: 'r16',
        productid: 'p107',
        userName: 'Paul Anderson',
        userImageUrl: 'https://randomuser.me/api/portraits/men/2.jpg',
        rating: 4,
        title: 'Pretty good',
        comment: 'Met my needs, decent build.',
        reviewDate: new Date('2024-09-20'),
      },
    ],
  },
  {
    id: 'p4',
    name: 'Smart Watch Series 7',
    description: 'Smartwatch with health monitoring and built-in GPS.',
    price: 279.99,
    imageUrl:
      '/photo-1760520338230-3074dded8778?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8U21hcnQlMjBXYXRjaCUyMFNlcmllcyUyMDd8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&q=60&w=300',
    rating: 4.7,
    reviewsCount: 780,
    inStock: true,
    category: 'electronics',
    reviews: [
      {
        id: 'r4',
        productid: 'p101',
        userName: 'Daniel Wu',
        userImageUrl: 'https://randomuser.me/api/portraits/men/5.jpg',
        rating: 5,
        title: 'Perfect!',
        comment: 'Exactly what I needed, great value.',
        reviewDate: new Date('2024-03-20'),
      },
    ],
  },
  {
    id: 'p5',
    name: 'Ceramic Coffee Mug',
    description: 'Handmade ceramic mug with a matte finish.',
    price: 19.99,
    imageUrl:
      '/photo-1666445759502-85124c28524e?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8Q2VyYW1pYyUyMENvZmZlZSUyME11Z3xlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&q=60&w=300',
    rating: 4.3,
    reviewsCount: 82,
    inStock: true,
    category: 'kitchen',
    reviews: [
      {
        id: 'r5',
        productid: 'p102',
        userName: 'Emma Brown',
        userImageUrl: 'https://randomuser.me/api/portraits/women/12.jpg',
        rating: 2,
        title: 'Not great',
        comment: 'Stopped working after a week.',
        reviewDate: new Date('2024-04-01'),
      },
      {
        id: 'r17',
        productid: 'p108',
        userName: 'Quinn Taylor',
        userImageUrl: 'https://randomuser.me/api/portraits/women/22.jpg',
        rating: 5,
        title: 'Amazing!',
        comment: 'Best purchase this year.',
        reviewDate: new Date('2024-10-01'),
      },
    ],
  },
  {
    id: 'p6',
    name: 'Portable Blender',
    description: 'Portable blender for smoothies and shakes.',
    price: 49.99,
    imageUrl:
      '/photo-1570222094114-d054a817e56b?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8YmxlbmRlcnxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&q=60&w=300',
    rating: 4.4,
    reviewsCount: 260,
    inStock: false,
    category: 'kitchen',
    reviews: [
      {
        id: 'r6',
        productid: 'p102',
        userName: 'Frank Miller',
        userImageUrl: 'https://randomuser.me/api/portraits/men/4.jpg',
        rating: 4,
        title: 'Good purchase',
        comment: 'Happy with the product overall.',
        reviewDate: new Date('2024-04-18'),
      },
    ],
  },
  {
    id: 'p7',
    name: 'Leather Notebook',
    description: 'Leather-bound notebook with high-quality paper.',
    price: 24.99,
    imageUrl:
      '/photo-1689757875266-66446af145dc?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8TGVhdGhlciUyME5vdGVib29rfGVufDB8fDB8fHww&auto=format&fit=crop&q=60&w=300',
    rating: 4.8,
    reviewsCount: 150,
    inStock: true,
    category: 'office',
    reviews: [
      {
        id: 'r7',
        productid: 'p103',
        userName: 'Grace Lee',
        userImageUrl: 'https://randomuser.me/api/portraits/women/18.jpg',
        rating: 5,
        title: 'Love it!',
        comment: 'Stylish and functional, worth every penny.',
        reviewDate: new Date('2024-05-02'),
      },
      {
        id: 'r18',
        productid: 'p108',
        userName: 'Rachel Evans',
        userImageUrl: 'https://randomuser.me/api/portraits/women/70.jpg',
        rating: 3,
        title: 'Average',
        comment: 'It’s fine, but nothing special.',
        reviewDate: new Date('2024-10-15'),
      },
    ],
  },
  {
    id: 'p8',
    name: 'Modern Floor Lamp',
    description: 'Tall Scandinavian-style floor lamp.',
    price: 139.0,
    imageUrl:
      '/photo-1758380388531-3ce641e4b2d8?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8TW9kZXJuJTIwRmxvb3IlMjBMYW1wfGVufDB8fDB8fHww&auto=format&fit=crop&q=60&w=300',
    rating: 4.4,
    reviewsCount: 97,
    inStock: true,
    category: 'home',
    reviews: [
      {
        id: 'r8',
        productid: 'p103',
        userName: 'Henry Adams',
        userImageUrl: 'https://randomuser.me/api/portraits/men/40.jpg',
        rating: 3,
        title: 'Decent',
        comment: 'Does the job, but nothing special.',
        reviewDate: new Date('2024-05-15'),
      },

      {
        id: 'r19',
        productid: 'p109',
        userName: 'Samuel Green',
        userImageUrl: 'https://randomuser.me/api/portraits/men/46.jpg',
        rating: 4,
        title: 'Good product',
        comment: 'Works as expected, happy with it.',
        reviewDate: new Date('2024-11-01'),
      },
    ],
  },
  {
    id: 'p9',
    name: 'Bluetooth Speaker',
    description: 'Compact speaker with deep sound and water resistance.',
    price: 59.99,
    imageUrl:
      '/photo-1547052178-7f2c5a20c332?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fEJsdWV0b290aCUyMFNwZWFrZXJ8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&q=60&w=300',
    rating: 4.6,
    reviewsCount: 403,
    inStock: true,
    category: 'electronics',
    reviews: [
      {
        id: 'r9',
        productid: 'p104',
        userName: 'Isabella Rossi',
        userImageUrl: 'https://randomuser.me/api/portraits/women/31.jpg',
        rating: 4,
        title: 'Satisfied',
        comment: 'Good quality, fast delivery.',
        reviewDate: new Date('2024-06-01'),
      },
    ],
  },
  {
    id: 'p10',
    name: 'Stainless Steel Knife Set',
    description: 'Stainless steel knife set with a wooden block stand.',
    price: 79.49,
    imageUrl:
      '/photo-1560291544-bc203f6f95be?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8U3RhaW5sZXNzJTIwU3RlZWwlMjBLbmlmZSUyMFNldHxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&q=60&w=500',
    rating: 4.5,
    reviewsCount: 231,
    inStock: true,
    category: 'kitchen',
    reviews: [
      {
        id: 'r10',
        productid: 'p104',
        userName: 'Jack Wilson',
        userImageUrl: 'https://randomuser.me/api/portraits/men/48.jpg',
        rating: 1,
        title: 'Disappointed',
        comment: 'Arrived broken, poor packaging.',
        reviewDate: new Date('2024-06-10'),
      },

      {
        id: 'r20',
        productid: 'p109',
        userName: 'Tina White',
        userImageUrl: 'https://randomuser.me/api/portraits/women/29.jpg',
        rating: 5,
        title: 'Perfect choice',
        comment: 'Exactly what I wanted, flawless.',
        reviewDate: new Date('2024-11-20'),
      },
    ],
  },
  {
    id: 'p11',
    name: 'Smart 4K TV',
    description: 'Compact speaker with deep sound and water resistance.',
    price: 59.99,
    imageUrl:
      '/photo-1730909352933-614f1673ac21?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8U21hcnQlMjA0SyUyMFRWfGVufDB8fDB8fHww&auto=format&fit=crop&q=60&w=300',
    rating: 4.6,
    reviewsCount: 403,
    inStock: true,
    category: 'electronics',
    reviews: [
      {
        id: 'r11',
        productid: 'p105',
        userName: 'Karen Davis',
        userImageUrl: 'https://randomuser.me/api/portraits/women/51.jpg',
        rating: 5,
        title: 'Fantastic!',
        comment: 'Would buy again without hesitation.',
        reviewDate: new Date('2024-07-01'),
      },
    ],
  },
  {
    id: 'p12',
    name: 'Professional Camera',
    description: 'Compact speaker with deep sound and water resistance.',
    price: 59.99,
    imageUrl:
      '/photo-1474376700777-eb547d9bed2f?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8UHJvZmVzc2lvbmFsJTIwQ2FtZXJhfGVufDB8fDB8fHww&auto=format&fit=crop&q=60&w=300',
    rating: 4.6,
    reviewsCount: 403,
    inStock: true,
    category: 'electronics',
    reviews: [
      {
        id: 'r12',
        productid: 'p105',
        userName: 'Leo Martinez',
        userImageUrl: 'https://example.com/users/leo.jpg',
        rating: 4,
        title: 'Good value',
        comment: 'Affordable and reliable.',
        reviewDate: new Date('2024-07-12'),
      },
    ],
  },
  {
    id: 'p13',
    name: 'Robot Vacuum',
    description: 'Tall Scandinavian-style floor lamp.',
    price: 139.0,
    imageUrl:
      '/photo-1600322305530-45714a0bc945?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8Um9ib3QlMjBWYWN1dW18ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&q=60&w=300',
    rating: 4.4,
    reviewsCount: 97,
    inStock: true,
    category: 'home',
    reviews: [
      {
        id: 'r13',
        productid: 'p106',
        userName: 'Mia Chen',
        userImageUrl: 'https://randomuser.me/api/portraits/women/11.jpg',
        rating: 3,
        title: 'Okay',
        comment: 'Not bad, but could be better.',
        reviewDate: new Date('2024-08-01'),
      },
      {
        id: 'r14',
        productid: 'p106',
        userName: 'Noah Thompson',
        userImageUrl: 'https://randomuser.me/api/portraits/women/35.jpg',
        rating: 5,
        title: 'Highly recommend',
        comment: 'Exceeded expectations in every way.',
        reviewDate: new Date('2024-08-15'),
      },
    ],
  },
];
